parameters:
  agentOs: 'Windows'
  poolVmImage: ''
  beforeBuild: []
  afterBuild: []
  timeoutInMinutes: 60

jobs:
- job: ${{ coalesce(parameters.jobName, parameters.agentOs) }}
  displayName: ${{ coalesce(parameters.jobDisplayName, parameters.agentOs) }}
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  pool:
    ${{ if ne(parameters.poolVmImage, '') }}:
      vmImage: ${{ parameters.poolVmImage }}
    ${{ if and(eq(parameters.poolVmImage, ''), eq(parameters.agentOs, 'macOS')) }}:
      vmImage: macOS-10.13
    ${{ if and(eq(parameters.poolVmImage, ''), eq(parameters.agentOs, 'Linux')) }}:
      vmImage: ubuntu-16.04
  steps:
  - checkout: self
    clean: true
  
  - ${{ parameters.beforeBuild }}
  
  - ${{ parameters.afterBuild }}